ips:
  - 192.168.199.129
credentials:
  - username: elliot
    password: fsociety
  - username: mrrobot
    password: mrrobot
  - username: trenton
    password: trenton
  - username: darlene
    password: darlene
  - username: leslie
    password: leslie
  - username: mobley
    password: mobley
