ip_list_url: "http://192.168.65.1:8000/clients.txt"
root_netcat_server_port: 42069
ips:
  - 192.168.199.129
credentials:
  - username: elliot
    password: fsociety
    sudo_user: True
  - username: mrrobot
    password: mrrobot
    sudo_user: True
  - username: trenton
    password: trenton
    sudo_user: False
  - username: darlene
    password: darlene
    sudo_user: False
  - username: leslie
    password: leslie
    sudo_user: False
  - username: mobley
    password: mobley
    sudo_user: False
